### ISSUE TITLE
How does this solution differ from using css variables?

### ISSUE THREAD

**Issue by billdwhite** [lVlyke/lithium-ngx-material-theming#2]
I've install your library and got it working because I need to allow users to create themes that can be used at runtime dynamically and your library does indeed allow that.  However,[ I read about using css variables to do something similar](https://medium.com/angular-in-depth/build-truly-dynamic-theme-with-css-variables-539516e95837).  How does this library differ from that?  

also: is there any way to allow users to create and use themes dynamically at runtime without having to run the 'ltc' pre-compilation?

**Comment by lVlyke** [comment]
Great question. The CSS variable solution would indeed solve many of the same problems that this library solves. However, an issue with CSS variables is that they are not natively supported in legacy browsers like Internet Explorer. There are polyfills available that enable limited usage of CSS variables in IE, but, at least from my own experiences, the limitations of the available CSS variable polyfill solutions aren’t flexible enough to allow for things like applying multiple themes at runtime to different parts of the app, something this library does support.

If legacy browser and nested theme support isn’t something you need, though, the CSS variable approach should work equally as well as this library.

Explicit theme template compilation with `ltc` is only required if you’re adding your own custom theme CSS extensions to the base Angular Material theme CSS. However, if you’re just using the base Angular Material CSS, you can simply include the [@lithiumjs/ngx-material-theming-templates](https://www.npmjs.com/package/@lithiumjs/ngx-material-theming-templates) dependency in your project, which is a pre-compiled theme template that has been generated from the base Angular Material styles. When this dependency is included, you can call `ThemeGenerator.create` at runtime with your user-defined themes without having to manually invoke `ltc` in your build phase. 

If you want to avoid the concept of loading in offline theme templates altogether, though, there isn’t really a way around it. `ltc` is simply a convenience wrapper around the `dart-sass` compiler, so in theory you could use something like [sass.js](https://github.com/medialize/sass.js) to directly compile the theme template at runtime in the browser. I can’t imagine this would be very performant, though.

Hope this helps.

**Comment by billdwhite** [comment]
Yes, your answer is extremely informative and helpful.   Thanks so much for the insights.

**Comment by billdwhite** [comment]
One other question to follow up on this: in addition to the ability to support older browsers, would another benefit be the ability to dynamically use dark and light themes?  I was trying to figure out a way to switch between them in sass by calling mat-dark-theme/mat-light-theme based on a css variable but I do not think it will work due to the one way flow of sass-css.  Would that be another factor in choosing this solution?

**Comment by billdwhite** [comment]
actually, I think figured out that you can use a general css class of light/dark at the top of the dom and have SASS use that class to determine which mat-light-theme/mat-dark-theme to use.
